default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres

development:
  <<: *default
  database: tlmld_development

test:
  <<: *default
  database: tlmld_test

production:
  <<: *default
  database: tlmld
  username: tlmld
  password: <%= ENV['TLMLD_DATABASE_PASSWORD'] %>
